### ISSUE TITLE
Add delay, to prevent deleted showcases from being mirrored

### ISSUE THREAD

**Issue by SirLich** [Hatchibombotar/WebhookShowcaseBot#1]
We have moderation in place which deletes showcases matching some criterias:
 - Spam links
 - Messages without any images/links

The issue is the bot is too fast, causing these messages to be preserved in #showcase-discussion

**Comment by Hatchibombotar** [comment]
https://github.com/Bedrock-OSS/webhook-showcase-bot/commit/a8f4f69b48f12e7521eb1f5ba5aed1c36ac93821
